# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sum_in_temp <- function(x, y, tmp_vec) {
    .Call(`_bigutilsr_sum_in_temp`, x, y, tmp_vec)
}

sub_in_temp <- function(x, y, tmp_vec) {
    .Call(`_bigutilsr_sub_in_temp`, x, y, tmp_vec)
}

scaleTau2_vector_rcpp <- function(x, tmp_dev, tmp_med) {
    .Call(`_bigutilsr_scaleTau2_vector_rcpp`, x, tmp_dev, tmp_med)
}

dist_scaleTau2_matrix_rcpp <- function(Z) {
    .Call(`_bigutilsr_dist_scaleTau2_matrix_rcpp`, Z)
}

roll_mean <- function(x, w) {
    .Call(`_bigutilsr_roll_mean`, x, w)
}

rowSumsSq <- function(source) {
    .Call(`_bigutilsr_rowSumsSq`, source)
}

